source 'https://rubygems.org'

gem 'gollum'

# Support for extra markups
gem 'asciidoctor' # AsciiDoc
gem 'creole'      # Creole
gem 'wikicloth'   # MediaWiki
gem 'org-ruby'    # Org
gem 'RedCloth'    , '>= 4.3.3' # Textile
