source 'https://rubygems.org'

gem 'sensu'

# integration
gem 'sensu-plugins-influxdb', '>= 2.0.0'

# checks
gem 'sensu-plugins-http', '>= 3.0.0'
gem 'sensu-plugins-disk-checks', '>= 5.0.0'
gem 'sensu-plugins-logs', '>= 2.0.0'
gem 'sensu-plugins-systemd', '>= 0.2.0'
# gem 'sensu-plugins-process-checks'
